name: pr_tec_academy
description: PR TEC Academy - Learn Programming with Flutter Web
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  
  # UI & Animations
  flutter_animate: ^4.5.0
  animated_text_kit: ^4.2.2
  flutter_hooks: ^0.20.3
  responsive_framework: ^1.4.0
  
  # Icons
  line_icons: ^2.0.3
  lucide_icons: ^0.257.0
  
  # Navigation
  go_router: ^13.0.0
  
  # Forms & Validation
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
  
  # Lottie animations
  lottie: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/fonts/
